server:
  port: 9000
spring:
  application:
    name: websocket-chat
  datasource:
    url: jdbc:mysql://localhost:3306/websocket-chat?serverTimezone=CST&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.127.119